CustomerService/Controllers/CustServiceSlotController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration.Design;
using System.Linq;
using System.Threading.Tasks;
using Therapi.Utility;
using TherapiCareTest.Data;
using TherapiCareTest.Models;
using TherapiCareTest.ViewModels;

namespace TherapiCareTest.Areas.CustomerService.Controllers
{
    [Area("CustomerService")]
    [Authorize(Roles = SD.Role_CustomerService)]
    public class CustServiceSlotController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustServiceSlotController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int sessionId)
        {
            var session = await _context.Sessions
               .FirstOrDefaultAsync(s => s.Id == sessionId);

            if (session == null)
            {
                return NotFound();
            }

            var slots = await _context.Slots
                .Include(s => s.Therapist)
                .Where(s => s.SessionId == sessionId)
                .ToListAsync();

            var viewModel = new SessionSlotVM
            {
                SessionId = sessionId,
                SessionName = session.Name,
                Slots = slots
            };
            return View(viewModel);
        }

        public async Task<IActionResult> Create(int sessionId)
        {
            var session = await _context.Sessions
               .FirstOrDefaultAsync(s => s.Id == sessionId);

            if (session == null)
            {
                return NotFound();
            }

            var therapistList = await _context.Therapists
                .Select(t => new SelectListItem
                {
                    Value = t.TherapistId,
                    Text = t.Name
                })
                .ToListAsync();

            var viewModel = new SlotVM
            {
                Slot = new Slot
                {
                    SessionId = sessionId
                },
                TherapistList = therapistList
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SlotVM viewModel)
        {
            var startTime = viewModel.Slot.StartTime.TimeOfDay;
            var endTime = viewModel.Slot.EndTime.TimeOfDay;

            Console.WriteLine($"Start Time: {startTime}, End Time: {endTime}");

            if (startTime < TimeSpan.FromHours(8) || endTime > TimeSpan.FromHours(17))
            {
                ModelState.AddModelError("", "Time must be between 8am and 5pm.");
                Console.WriteLine("Validation failed: Time must be between 8am and 5pm.");
                return View(viewModel);
            }
            if (ModelState.IsValid)
            {
                _context.Add(viewModel.Slot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { sessionId = viewModel.Slot.SessionId });
            }

            viewModel.TherapistList = await _context.Therapists
                .Select(t => new SelectListItem
                {
                    Value = t.TherapistId,
                    Text = t.Name
                })
                .ToListAsync();

            return View(viewModel);
        }


        public async Task<IActionResult> Edit(int id, int sessionId)
        {

            var slot = await _context.Slots.FindAsync(id);
            if (slot == null)
            {
                return NotFound();
            }
            var session = await _context.Sessions
               .FirstOrDefaultAsync(s => s.Id == sessionId);

            if (session == null)
            {
                return NotFound();
            }
            var therapistList = await _context.Therapists
                .Select(t => new SelectListItem
                {
                    Value = t.TherapistId,
                    Text = t.Name
                })
                .ToListAsync();

            var viewModel = new SlotVM
            {
                Slot = slot,
                TherapistList = therapistList
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SlotVM viewModel)
        {
            if (id != viewModel.Slot.Id)
            {
                return NotFound();
            }

            var session = await _context.Sessions.FirstOrDefaultAsync(s => s.Id == viewModel.Slot.SessionId);
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel.Slot);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), new { sessionId = viewModel.Slot.SessionId });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SlotExists(viewModel.Slot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            viewModel.TherapistList = await _context.Therapists
                .Select(t => new SelectListItem
                {
                    Value = t.TherapistId,
                    Text = t.Name
                })
                .ToListAsync();

            return View(viewModel);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var slot = await _context.Slots
                .Include(s => s.Therapist)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (slot == null)
            {
                return NotFound();
            }

            return View(slot);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var slot = await _context.Slots.FindAsync(id);
            if (slot == null)
            {
                return NotFound();
            }

            _context.Slots.Remove(slot);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index), new { sessionId = slot.SessionId });
        }
    
        private bool SlotExists(int id)
        {
            return _context.Slots.Any(e => e.Id == id);
        }
    }
}

CustomerService/Controllers/CustServiceTherapyProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Therapi.Utility;
using TherapiCareTest.Data;
using TherapiCareTest.Models;
using TherapiCareTest.Repository.IRepository;

namespace TherapiCareTest.Areas.CustomerService.Controllers
{
    [Area("CustomerService")]
    [Authorize(Roles = SD.Role_CustomerService)]
    public class CustServiceTherapyProgramController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CustServiceTherapyProgramController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<TherapyProgram> objTherapyProgramList = _unitOfWork.TherapyProgram.GetAll().ToList();
            return View(objTherapyProgramList);
        }
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            TherapyProgram? therapyProgramFromDb = _unitOfWork.TherapyProgram.Get(u => u.Id == id);

            if (therapyProgramFromDb == null)
            {
                return NotFound();
            }
            return View(therapyProgramFromDb);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TherapyProgram obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.TherapyProgram.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Program created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            TherapyProgram? therapyProgramFromDb = _unitOfWork.TherapyProgram.Get(u => u.Id == id);
            //Category? categoryFromDb1 = _db.Categories.FirstOrDefault(u=>u.Id==id);
            //Category? categoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();

            if (therapyProgramFromDb == null)
            {
                return NotFound();
            }
            return View(therapyProgramFromDb);
        }
        [HttpPost]
        public IActionResult Edit(TherapyProgram obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.TherapyProgram.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Program updated successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    TherapyProgram? therapyProgramFromDb = _unitOfWork.TherapyProgram.Get(u => u.Id == id);

        //    if (therapyProgramFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(therapyProgramFromDb);
        //}


        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePOST(int? id)
        //{
        //    TherapyProgram? obj = _unitOfWork.TherapyProgram.Get(u => u.Id == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    _unitOfWork.TherapyProgram.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Program deleted successfully";
        //    return RedirectToAction("Index");
        //}
        #region API CALLS

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.TherapyProgram.Get(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.TherapyProgram.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Program deleted successfully" });
        }
        #endregion  
    }
}

CustomerService/Controllers/CustServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TherapiCareTest.Data;
using TherapiCareTest.Models;

namespace TherapiCareTest.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.SignalR;
    //using therapicare.Hubs; // Ensure this namespace matches your actual namespace for ChatHub
    using System.Threading.Tasks;
    using Therapi.Utility;

    namespace TherapiCareTest.Areas.CustomerService.Controllers
    {
        [Area("CustomerService")]
        [Authorize(Roles = SD.Role_CustomerService)]
        public class CustServicesController : Controller
        {
            private readonly IHubContext<ChatHub> _chatHubContext;

            public CustServicesController(IHubContext<ChatHub> chatHubContext)
            {
                _chatHubContext = chatHubContext;
            }

            // GET: /CustService/CustServices/Index
            public IActionResult Index()
            {
                return View();
            }

            // POST: /CustService/CustServices/SendMessage
            [HttpPost]
            public async Task<IActionResult> SendMessage(string user, string message)
            {
                if (string.IsNullOrEmpty(user) || string.IsNullOrEmpty(message))
                {
                    return BadRequest("User and message cannot be empty");
                }

                // For demonstration purposes, assuming customer service name is "Customer Service"
                user = "Customer Service";

                await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", user, message);
                return Ok();
            }
        }
    }

}

CustomerService/Views/CustServiceSlot/Create.cshtml
@model TherapiCareTest.ViewModels.SlotVM
<!-- Menu -->

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="CustServices" asp-action="Index" class="app-brand-link">
            <span class="app-brand-text demo menu-text fw-bolder ms-2">TherapiCare</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item">
            <a asp-area="CustomerService" asp-controller="CustServices" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-chat-dots-fill me-2"></i>
                <div data-i18n="Analytics"> Customer Service Chat</div>
            </a>
        </li>
        <li class="menu-item ">
            <a asp-area="CustomerService" asp-controller="CustomerServices" asp-action="ApproveReport" class="menu-link">
                <i class="flex-shrink-0 bi bi-file-earmark-text-fill me-2"></i>
                <div data-i18n="Analytics"> Report Approval</div>
            </a>
        </li>
        <li class="menu-item active">
            <a asp-area="CustomerService" asp-controller="CustServiceTherapyProgram" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bx bx-collection me-2"></i>
                <div data-i18n="Analytics"> Manage Program</div>
            </a>
        </li>


    </ul>
</aside>
<!-- / Menu -->
<!-- Navbar -->

<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
     id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        @* <div class="navbar-nav align-items-center">
        <div class="nav-item d-flex align-items-center">
        <i class="bx bx-search fs-4 lh-0"></i>
        <input type="text"
        class="form-control border-0 shadow-none"
        placeholder="Search..."
        aria-label="Search..." />
        </div>
        </div> *@
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">


            <!-- User -->
            @* <li class="nav-item navbar-dropdown dropdown-user dropdown">
            <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
            <div class="avatar avatar-online">
            <img src="../assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
            </div>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
            <li>
            <a class="dropdown-item" href="#">
            <div class="d-flex">
            <div class="flex-shrink-0 me-3">
            <div class="avatar avatar-online">
            <img src="../assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
            </div>
            </div>
            <div class="flex-grow-1">
            <span class="fw-semibold d-block">John Doe</span>
            <small class="text-muted">Admin</small>
            </div>
            </div>
            </a>
            </li>
            <li>
            <div class="dropdown-divider"></div>
            </li>
            <li>
            <a class="dropdown-item" href="#">
            <i class="bx bx-user me-2"></i>
            <span class="align-middle">My Profile</span>
            </a>
            </li>
            <li>
            <a class="dropdown-item" href="#">
            <i class="bx bx-cog me-2"></i>
            <span class="align-middle">Settings</span>
            </a>
            </li>
            <li>
            <a class="dropdown-item" href="#">
            <span class="d-flex align-items-center align-middle">
            <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
            <span class="flex-grow-1 align-middle">Billing</span>
            <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
            </span>
            </a>
            </li>
            <li>
            <div class="dropdown-divider"></div>
            </li>
            <li>
            <a class="dropdown-item" href="auth-login-basic.html">
            <i class="bx bx-power-off me-2"></i>
            <span class="align-middle">Log Out</span>
            </a>
            </li>
            </ul>
            </li> *@
            <!--/ User -->
        </ul>
    </div>
</nav>

<!-- / Navbar -->
<div class="card-body p-4">
    <div class="row pb-3">
        <div class="col-6">
            <h3 class="fw-bold py-3 mb-2"><span class="text-muted fw-light">Slot /</span> Create Slot</h3>
        </div>
        <div class="row">
            <div class="col-md-6">
                <form asp-action="Create">
                    <div class="form-group">
                        <label asp-for="Slot.StartTime" class="control-label"></label>
                        <input asp-for="Slot.StartTime" id="StartTime" class="form-control" value='@DateTime.Today.ToString("yyyy-MM-dd")' />
                        <span asp-validation-for="Slot.StartTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Slot.EndTime" class="control-label"></label>
                        <input asp-for="Slot.EndTime" id="EndTime"  class="form-control" value='@DateTime.Today.ToString("yyyy-MM-dd")' />
                        <span asp-validation-for="Slot.EndTime" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <select asp-for="Slot.TherapistId" asp-items="@Model.TherapistList" class="form-select border-0 shadow">
                            <option disabled selected>--Select Therapist--</option>
                        </select>
                        <label asp-for="Slot.TherapistId" class="control-label"></label>
                        <span asp-validation-for="Slot.TherapistId" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="Slot.SessionId" />
                    <br />
                    <div class="row pt-2">
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary form-control">Save</button>
                    </div>
                    <div class="col-md-6">
                        <a asp-controller="CustServiceSlot" asp-action="Index" asp-route-sessionId="@Model.Slot.SessionId" class="btn btn-secondary form-control">Back to list</a>
                    </div>
                    </div>
                    </form>
            </div>
        </div>

        @section Scripts {
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var today = new Date();
                    today.setDate(today.getDate() + 1); // tomorrow

                    document.getElementById('StartTime').min = today.toISOString().split('T')[0];
                    document.getElementById('EndTime').min = today.toISOString().split('T')[0];
                });
            </script>
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }

CustomerService/Views/CustServiceSlot/Details.cshtml
@model TherapiCareTest.Models.Slot
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Slot</h4>
    <hr />
    <dl class="row">
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CustomerService/Views/CustServiceSlot/Edit.cshtml
@model TherapiCareTest.ViewModels.SlotVM

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="CustServices" asp-action="Index" class="app-brand-link">
            <span class="app-brand-text demo menu-text fw-bolder ms-2">TherapiCare</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item">
            <a asp-area="CustomerService" asp-controller="CustServices" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-chat-dots-fill me-2"></i>
                <div data-i18n="Analytics"> Customer Service Chat</div>
            </a>
        </li>
        <li class="menu-item ">
            <a asp-area="CustomerService" asp-controller="CustomerServices" asp-action="ApproveReport" class="menu-link">
                <i class="flex-shrink-0 bi bi-file-earmark-text-fill me-2"></i>
                <div data-i18n="Analytics"> Report Approval</div>
            </a>
        </li>
        <li class="menu-item active">
            <a asp-area="CustomerService" asp-controller="CustServiceTherapyProgram" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bx bx-collection me-2"></i>
                <div data-i18n="Analytics"> Manage Program</div>
            </a>
        </li>


    </ul>
</aside>

<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
     id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        @* <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center">
                <i class="bx bx-search fs-4 lh-0"></i>
                <input type="text"
                       class="form-control border-0 shadow-none"
                       placeholder="Search..."
                       aria-label="Search..." />
            </div>
        </div> *@
        <!-- /Search -->

        @* <ul class="navbar-nav flex-row align-items-center ms-auto">


            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        <img src="../assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="#">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        <img src="../assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <span class="fw-semibold d-block">John Doe</span>
                                    <small class="text-muted">Admin</small>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="bx bx-cog me-2"></i>
                            <span class="align-middle">Settings</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <span class="d-flex align-items-center align-middle">
                                <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                                <span class="flex-grow-1 align-middle">Billing</span>
                                <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" href="auth-login-basic.html">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        @* </ul> *@
    </div>
</nav>

<div class="card-body p-4">
    <div class="row pb-3">
        <div class="col-6">
            <h3 class="fw-bold py-3 mb-2"><span class="text-muted fw-light">Slot /</span> Edit Slot</h3>
        </div>
        <hr />

    <div class="row">
        <div class="col-md-12">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-floating py-2 col-12">
                    <label asp-for="Slot.StartTime" class="control-label"></label>
                    <input asp-for="Slot.StartTime" id="StartTime" class="form-control" value='@DateTime.Today.ToString("yyyy-MM-dd")' />
                    <span asp-validation-for="Slot.StartTime" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <label asp-for="Slot.EndTime" class="control-label"></label>
                    <input asp-for="Slot.EndTime" id="EndTime" class="form-control" value='@DateTime.Today.ToString("yyyy-MM-dd")' />
                    <span asp-validation-for="Slot.EndTime" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <select asp-for="Slot.TherapistId" asp-items="@Model.TherapistList" class="form-select border-0 shadow">
                        <option disabled selected>--Select Therapist--</option>
                    </select>
                    <label asp-for="Slot.TherapistId" class="control-label"></label>
                    <span asp-validation-for="Slot.TherapistId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Slot.Id" />
                <input type="hidden" asp-for="Slot.SessionId" />
                <div class="row pt-2">
                    <div class="col-6 col-md-6">
                        <button type="submit" class="btn btn-primary form-control">Edit</button>
                    </div>
                    <div class="col-6 col-md-6">
                            <a asp-controller="CustServiceSlot" asp-action="Index" asp-route-sessionId="@Model.Slot.SessionId" class="btn btn-secondary form-control">Back to list</a>
                    </div>
                </div>
            </form>
        </div>
    </div>


    @section Scripts {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var today = new Date();
                today.setDate(today.getDate() + 1); // tomorrow

                document.getElementById('StartTime').min = today.toISOString().split('T')[0];
                document.getElementById('EndTime').min = today.toISOString().split('T')[0];
            });
        </script>
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }