Parent/Controllers/AnnouncementsController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Therapi.Utility;
using TherapiCareTest.Data;

namespace TherapiCareTest.Areas.Parent.Controllers
{
    [Area("Parent")]
    [Authorize(Roles = SD.Role_Parent)]
    public class AnnouncementsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnnouncementsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Parent/Announcements
        public async Task<IActionResult> Index()
        {
            var announcements = await _context.Announcements.ToListAsync();
            return View(announcements);
        }

        // GET: Parent/Announcements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements.FindAsync(id);
            if (announcement == null)
            {
                return NotFound();
            }

            // Mark the announcement as viewed
            announcement.IsViewed = true;
            _context.SaveChanges(); // Save changes to update IsViewed status

            return View(announcement);
        }
    }
}

Parent/Controllers/CustServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Therapi.Utility;
using TherapiCareTest.Data;
using TherapiCareTest.Models;

namespace TherapiCareTest.Areas.Parent.Controllers
{
    [Area("Parent")]
    [Authorize(Roles = SD.Role_Parent)]
    public class CustServicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustServicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CustService/CustServices
        public IActionResult Index()
        {
            var parents = _context.Parents.ToList();
            return View(parents);
        }


    }
}

Parent/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Therapi.Utility;
using TherapiCareTest.Data;
using TherapiCareTest.Models;

namespace TherapiCareTest.Areas.Parent.Controllers
{
    [Area("Parent")]
    [Authorize(Roles = SD.Role_Parent)]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReportController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            // Retrieve the parent information
            var parent = await _context.Parents
                                       .Include(p => p.ApplicationUser)
                                       .Include(p => p.Students)
                                       .ThenInclude(s => s.Reports)
                                       .FirstOrDefaultAsync(p => p.ApplicationUserId == userId);


            if (parent == null)
            {
                return NotFound("Parent not found.");
            }

            var allReports = parent.Students
                .SelectMany(s => s.Reports)
                .ToList();

            return View(allReports);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Reports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }
    }
}

Parent/Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using TherapiCareTest.Data;
using TherapiCareTest.Models;
using TherapiCareTest.ViewModels;
using System;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Therapi.Utility;

namespace TherapiCareTest.Controllers
{
    [Area("Parent")]
    [Authorize(Roles = SD.Role_Parent)]
    public class ScheduleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ScheduleController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var parent = await _context.Parents.FirstOrDefaultAsync(p => p.ApplicationUserId == userId);

            if (parent == null)
            {
                return NotFound();
            }

            var schedules = await _context.Schedules
        .Where(s => s.ProgramStudent.Student.ParentId == parent.ParentId) 
        .Include(s => s.Slot)
            .ThenInclude(slot => slot.Session)
        .Include(s => s.ProgramStudent)
            .ThenInclude(ps => ps.Student)
        .Include(s => s.ProgramStudent.TherapyProgram)
        .Include(s => s.Slot.Therapist)
        .ToListAsync();

            var scheduleVMs = schedules.Select(s => new ScheduleVM
            {
                Schedule = s,
                StudentName = s.ProgramStudent.Student.Name,
                ProgramName = s.ProgramStudent.TherapyProgram.Name,
                SessionName = s.Slot.Session.Name,
                Price = (s.Slot.StartTime.DayOfWeek == DayOfWeek.Saturday || s.Slot.StartTime.DayOfWeek == DayOfWeek.Friday) ?
                s.ProgramStudent.TherapyProgram.WeekendPrice : s.ProgramStudent.TherapyProgram.WeekdayPrice
            }).ToList();

            return View(scheduleVMs);
        }

        public async Task<IActionResult> Create(int programStudentId, int sessionId)
        {
            var programStudent = await _context.ProgramStudents
                .Include(ps => ps.Student)
                .Include(ps => ps.TherapyProgram)
                .FirstOrDefaultAsync(ps => ps.Id == programStudentId);

            if (programStudent == null)
            {
                return NotFound();
            }

            var session = await _context.Sessions
                .FirstOrDefaultAsync(s => s.Id == sessionId);

            if (session == null)
            {
                return NotFound();
            }

            var slots = await _context.Slots
        .Where(s => s.SessionId == sessionId)
        .Include(s => s.Therapist)
        .ToListAsync();

            var scheduledSlotIds = await _context.Schedules
                .Where(s => s.Slot.SessionId == sessionId)
                .Select(s => s.SlotId)
                .ToListAsync();
            var slotList = slots
                .Where(s => !scheduledSlotIds.Contains(s.Id))
                .Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = $"<strong>Date: </strong> {s.StartTime:yyyy-MM-dd} <br/> " +
                   $"<strong>Time: </strong> {s.StartTime:hh:mm tt} - {s.EndTime:hh:mm tt} <br/> " +
                   $"<strong>Therapist</strong>: {s.Therapist.Name} <br/> " +
                   $"<strong>Price</strong>: {(s.StartTime.DayOfWeek == DayOfWeek.Saturday || s.StartTime.DayOfWeek == DayOfWeek.Friday ? programStudent.TherapyProgram.WeekendPrice : programStudent.TherapyProgram.WeekdayPrice):C}"
                })
                .ToList();

            if (slotList.Count == 0)
            {
                ViewData["NoSlotsMessage"] = "No slots available.";
            }

            var viewModel = new ScheduleVM
            {
                Schedule = new Schedule
                {
                    ProgramStudentId = programStudentId
                },
                StudentName = programStudent.Student.Name,
                ProgramName = programStudent.TherapyProgram.Name,
                SessionName = session.Name,
                SlotList = slotList
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ScheduleVM viewModel)
        {
            if (ModelState.IsValid)
            {
                var slot = await _context.Slots
                    .Include(s => s.Therapist)
                    .FirstOrDefaultAsync(s => s.Id == viewModel.SelectedSlotId);

                if (slot == null)
                {
                    return NotFound();
                }

                var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var parent = await _context.Parents.FirstOrDefaultAsync(p => p.ApplicationUserId == currentUserId);

                if (parent == null)
                {
                    return NotFound("Parent not found.");
                }

                var programStudent = await _context.ProgramStudents
                    .Include(ps => ps.TherapyProgram)
                    .FirstOrDefaultAsync(ps => ps.Id == viewModel.Schedule.ProgramStudentId);

                if (programStudent == null)
                {
                    return NotFound();
                }

                var schedule = new Schedule
                {
                    ProgramStudentId = viewModel.Schedule.ProgramStudentId,
                    SlotId = viewModel.SelectedSlotId
                };
                _context.Add(schedule);
                await _context.SaveChangesAsync();

                var billing = new Billing
                {
                    Date = slot.StartTime,
                    TherapyProgramId = programStudent.ProgramId,
                    StudentId = programStudent.StudentId,
                    ParentId = parent.ParentId,
                    Amount = IsWeekend(slot.StartTime) ? programStudent.TherapyProgram.WeekendPrice : programStudent.TherapyProgram.WeekdayPrice,
                    PaymentReceipt = string.Empty 
                };

                _context.Billings.Add(billing);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            var session = await _context.Sessions
                .FirstOrDefaultAsync(s => s.Id == viewModel.Schedule.Slot.SessionId);

            if (session == null)
            {
                return NotFound();
            }

            viewModel.SlotList = await _context.Slots
                .Where(s => s.SessionId == session.Id)
                .Include(s => s.Therapist)
                .Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = $"{s.StartTime:yyyy-MM-dd HH:mm}  -  {s.EndTime:HH:mm} (Therapist: {s.Therapist.Name})"
                })
                .ToListAsync();

            return View(viewModel);
        }

        private bool IsWeekend(DateTime date)
        {
            var dayOfWeek = date.DayOfWeek;
            return dayOfWeek == DayOfWeek.Saturday || dayOfWeek == DayOfWeek.Sunday;
        }

        private bool ScheduleExists(int id)
        {
            return _context.Schedules.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Edit(int id, int sessionId)
        {
            var schedule = await _context.Schedules.FindAsync(id);
            if (schedule == null)
            {
                return NotFound();
            }

            var programStudent = await _context.ProgramStudents
                .Include(ps => ps.Student)
                .Include(ps => ps.TherapyProgram)
                .FirstOrDefaultAsync(ps => ps.Id == schedule.ProgramStudentId);

            if (programStudent == null)
            {
                return NotFound();
            }

            var session = await _context.Sessions
               .FirstOrDefaultAsync(s => s.Id == sessionId);

            if (session == null)
            {
                return NotFound();
            }

            var slots = await _context.Slots
       .Where(s => s.SessionId == sessionId)
       .Include(s => s.Therapist)
       .ToListAsync();

            var scheduledSlotIds = await _context.Schedules
                .Where(s => s.Slot.SessionId == sessionId)
                .Select(s => s.SlotId)
                .ToListAsync();
            var slotList = slots
                .Where(s => !scheduledSlotIds.Contains(s.Id))
                .Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = $"<strong>Date: </strong> {s.StartTime:yyyy-MM-dd} <br/> " +
                   $"<strong>Time: </strong> {s.StartTime:hh:mm tt} - {s.EndTime:hh:mm tt} <br/> " +
                   $"<strong>Therapist</strong>: {s.Therapist.Name} <br/> " +
                   $"<strong>Price</strong>: {(s.StartTime.DayOfWeek == DayOfWeek.Saturday || s.StartTime.DayOfWeek == DayOfWeek.Sunday ? programStudent.TherapyProgram.WeekendPrice : programStudent.TherapyProgram.WeekdayPrice):C}"
                })
                .ToList();

            if (slotList.Count == 0)
            {
                ViewData["NoSlotsMessage"] = "No slots available.";
            }

            var viewModel = new ScheduleVM

Parent/Views/Schedule/Create.cshtml
@model TherapiCareTest.ViewModels.ScheduleVM
<!-- Menu -->

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="Home" asp-action="Index" class="app-brand-link">
            <span class="app-brand-text demo menu-text fw-bolder ms-2">TherapiCare</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <li class="menu-item ">
            <a asp-area="Parent" asp-controller="Home" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-house-door-fill me-2"></i>
                <div data-i18n="Analytics"> Dashboard</div>
            </a>
        </li>

        <li class="menu-item">
            <a asp-area="Parent" asp-controller="Announcements" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-megaphone-fill me-2"></i>
                <div data-i18n="Analytics"> Announcement</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Parent" asp-controller="Billings" asp-action="Index" class="menu-link">
                <i class="menu-icon tf-icons bx bx-money"></i>
                <div data-i18n="Basic">Billings  </div>
                @if (ViewData["HasPendingBills"] != null && (bool)ViewData["HasPendingBills"])
                {

                    <span class="navbar-text text-danger">

                        <i class="bi bi-patch-exclamation-fill"></i>
                    </span>
                }
            </a>
        </li>
        <li class="menu-item active">
            <a asp-area="Parent" asp-controller="Schedule" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-calendar-event-fill me-2"></i>
                <div data-i18n="Analytics"> Schedule</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Parent" asp-controller="Student" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-person-square me-2"></i>
                <div data-i18n="Analytics"> My Children</div>
            </a>
        </li>
        <li class="menu-item ">
            <a asp-area="Parent" asp-controller="ProgramStudent" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-person-vcard-fill me-2"></i>
                <div data-i18n="Analytics"> Registered Program</div>
            </a>
        </li>
        <li class="menu-item ">
            <a asp-area="Parent" asp-controller="Report" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-file-earmark-fill me-2"></i>
                <div data-i18n="Analytics">Children Report</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Parent" asp-controller="CustServices" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-chat-dots-fill me-2"></i>
                <div data-i18n="Analytics"> Customer Service</div>
            </a>
        </li>
    </ul>
</aside>
<!-- / Menu -->
<!-- Navbar -->

<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
     id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        @* <div class="navbar-nav align-items-center">
        <div class="nav-item d-flex align-items-center">
        <i class="bx bx-search fs-4 lh-0"></i>
        <input type="text"
        class="form-control border-0 shadow-none"
        placeholder="Search..."
        aria-label="Search..." />
        </div>
        </div> *@
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">
        </ul>
    </div>
</nav>

<!-- / Navbar -->
<div class="card-body p-4">
    <div class="row pb-3">
        <div class="col-6">
            <h3 class="fw-bold py-3 mb-2"><span class="text-muted fw-light">Schedule /</span> @(Model.Schedule.Id != 0 ? "Update" : "New") Schedule</h3>
        </div>
        <hr />

        <div class="row">
            <div class="col-md-6">
                <form asp-action="Create" method="post" class="row" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ProgramName" class="control-label">Program Name</label>
                        <input asp-for="ProgramName" class="form-control" readonly />
                    </div>
                    <div class="form-group">
                        <label asp-for="StudentName" class="control-label">Student Name</label>
                        <input asp-for="StudentName" class="form-control" readonly />
                    </div>
                    <div class="form-group">
                        <label asp-for="SessionName" class="control-label">Session</label>
                        <input asp-for="SessionName" class="form-control" readonly />
                    </div>
                    <div class="form-group py-2 col-12">
                        <label class="control-label">Available Slots</label>
                        <div class="slot-selection-box">
                            @if (!string.IsNullOrEmpty(ViewData["NoSlotsMessage"] as string))
                            {
                                <div class="alert alert-warning" role="alert">
                                    @ViewData["NoSlotsMessage"]
                                </div>
                            }
                            @foreach (var slot in Model.SlotList)
                            {
                                <div class="form-check card mb-2 p-2 border-primary">
                                    <div class="card-body">
                                        <input type="radio" class="form-check-input" name="SelectedSlotId" value="@slot.Value" />
                                        <label class="form-check-label">
                                            @Html.Raw(slot.Text)<br />
                                        </label>
                                    </div>
                                </div>
                            }
                        </div>
                        <span asp-validation-for="SelectedSlotId" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="Schedule.Id" />
                    <input type="hidden" asp-for="Schedule.ProgramStudentId" />
                    <div class="form-group">
                        <input type="submit" value="Schedule" class="btn btn-primary" id="createButton" disabled />
                        <a asp-action="Index" asp-controller="ProgramStudent" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var createButton = document.getElementById('createButton');
                var radioButtons = document.querySelectorAll('input[name="SelectedSlotId"]');

                radioButtons.forEach(function (radio) {
                    radio.addEventListener('change', function () {
                        createButton.disabled = false;
                    });
                });
            });
        </script>
    }
</div>

<style>
    .slot-selection-box .card {
        border: 1px solid #007bff;
        background-color: #f8f9fa;
    }

        .slot-selection-box .card .card-body {
            display: flex;
            align-items: center;
        }

        .slot-selection-box .card .form-check-input {
            margin-right: 10px;
        }
</style>

Parent/Views/Schedule/Edit.cshtml
@model TherapiCareTest.ViewModels.ScheduleVM
<!-- Menu -->

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="Home" asp-action="Index" class="app-brand-link">
            <span class="app-brand-text demo menu-text fw-bolder ms-2">TherapiCare</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <li class="menu-item ">
            <a asp-area="Parent" asp-controller="Home" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-house-door-fill me-2"></i>
                <div data-i18n="Analytics"> Dashboard</div>
            </a>
        </li>

        <li class="menu-item">
            <a asp-area="Parent" asp-controller="Announcements" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-megaphone-fill me-2"></i>
                <div data-i18n="Analytics"> Announcement</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Parent" asp-controller="Billings" asp-action="Index" class="menu-link">
                <i class="menu-icon tf-icons bx bx-money"></i>
                <div data-i18n="Basic">Billings  </div>
                @if (ViewData["HasPendingBills"] != null && (bool)ViewData["HasPendingBills"])
                {

                    <span class="navbar-text text-danger">

                        <i class="bi bi-patch-exclamation-fill"></i>
                    </span>
                }
            </a>
        </li>
        <li class="menu-item active">
            <a asp-area="Parent" asp-controller="Schedule" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-calendar-event-fill me-2"></i>
                <div data-i18n="Analytics"> Schedule</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Parent" asp-controller="Student" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-person-square me-2"></i>
                <div data-i18n="Analytics"> My Children</div>
            </a>
        </li>
        <li class="menu-item ">
            <a asp-area="Parent" asp-controller="ProgramStudent" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-person-vcard-fill me-2"></i>
                <div data-i18n="Analytics"> Registered Program</div>
            </a>
        </li>
        <li class="menu-item ">
            <a asp-area="Parent" asp-controller="Report" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-file-earmark-fill me-2"></i>
                <div data-i18n="Analytics">Children Report</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Parent" asp-controller="CustServices" asp-action="Index" class="menu-link">
                <i class="flex-shrink-0 bx bi bi-chat-dots-fill me-2"></i>
                <div data-i18n="Analytics"> Customer Service</div>
            </a>
        </li>
    </ul>
</aside>
<!-- / Menu -->
<!-- Navbar -->

<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
     id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        @* <div class="navbar-nav align-items-center">
        <div class="nav-item d-flex align-items-center">
        <i class="bx bx-search fs-4 lh-0"></i>
        <input type="text"
        class="form-control border-0 shadow-none"
        placeholder="Search..."
        aria-label="Search..." />
        </div>
        </div> *@
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">
        </ul>
    </div>
</nav>

<!-- / Navbar -->
<div class="card-body p-4">
    <div class="row pb-3">
        <div class="col-6">
            <h3 class="fw-bold py-3 mb-2"><span class="text-muted fw-light">Schedule /</span> @(Model.Schedule.Id != 0 ? "Update" : "New") Schedule</h3>
        </div>
        <hr />

        <div class="row">
            <div class="col-md-6">
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Schedule.Id" />
    <input type="hidden" asp-for="Schedule.ProgramStudentId" />
    <div class="form-group">
        <label asp-for="StudentName" class="control-label">Student Name</label>
        <input asp-for="StudentName" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="ProgramName" class="control-label">Program Name</label>
        <input asp-for="ProgramName" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="SessionName" class="control-label">Session</label>
        <input asp-for="SessionName" class="form-control" readonly />
    </div>
    <div class="form-group py-2 col-12">
        <label class="control-label">Available Slots</label>
        <div class="slot-selection-box">
            @if (!string.IsNullOrEmpty(ViewData["NoSlotsMessage"] as string))
            {
                <div class="alert alert-warning" role="alert">
                    @ViewData["NoSlotsMessage"]
                </div>
            }
            @foreach (var slot in Model.SlotList)
            {
                <div class="form-check card mb-2 p-2 border-primary">
                    <div class="card-body">
                        <input type="radio" class="form-check-input" name="SelectedSlotId" value="@slot.Value" />
                        <label class="form-check-label">
                            @Html.Raw(slot.Text)<br />
                        </label>
                    </div>
                </div>
            }
        </div>
        <span asp-validation-for="SelectedSlotId" class="text-danger"></span>
    </div>
    
    <br />
    <button type="submit" class="btn btn-primary" id="saveButton" disabled>Save</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>
            </div>
        </div>
    </div>
<partial name="_ValidationScriptsPartial" />

    @section Scripts {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var saveButton = document.getElementById('saveButton');
                var radioButtons = document.querySelectorAll('input[name="SelectedSlotId"]');

                radioButtons.forEach(function (radio) {
                    radio.addEventListener('change', function () {
                        saveButton.disabled = false;
                    });
                });
            });
        </script>
    }