Admin/Controllers/BillingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Therapi.Utility;
using TherapiCareTest.Data;
using TherapiCareTest.Data.Enum;
using TherapiCareTest.Models;
using Rotativa.AspNetCore;
using TherapiCareTest.Services;


namespace TherapiCareTest.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class BillingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailService _emailService;

        public BillingsController(ApplicationDbContext context, IEmailService emailService)
        {
            _context = context;
            _emailService = emailService;
        }

        // GET: Admin/Billings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Billings.Include(b => b.Parent).Include(b => b.Student).Include(b => b.TherapyProgram);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Billings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billing = await _context.Billings
                .Include(b => b.Parent)
                .Include(b => b.Student)
                .Include(b => b.TherapyProgram)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (billing == null)
            {
                return NotFound();
            }

            return View(billing);
        }

        [HttpGet]
        public IActionResult Filter(int? selectedMonth, PaymentStatus? paymentStatus)
        {
            IQueryable<Billing> query = _context.Billings
                .Include(b => b.Parent)
                .Include(b => b.Student)
                .Include(b => b.TherapyProgram);

            if (selectedMonth.HasValue)
            {
                query = query.Where(b => b.Date.Month == selectedMonth.Value);
            }
            if (paymentStatus.HasValue)
            {
                query = query.Where(b => b.PaymentStatus == paymentStatus.Value);
            }

            var filteredBillings = query.ToList();
            decimal totalAmount = filteredBillings.Sum(b => Convert.ToDecimal(b.Amount));

            ViewData["TotalAmount"] = totalAmount;
            ViewData["SelectedMonth"] = selectedMonth;
            ViewData["SelectedPaymentStatus"] = paymentStatus;
            return PartialView("_BillingTablePartial", filteredBillings);
        }

        public IActionResult GeneratePdf(int? selectedMonth, PaymentStatus? paymentStatus)
        {
            // Fetch billings data with related entities included
            IQueryable<Billing> billingsQuery = _context.Billings
                .Include(b => b.Student)
                .Include(b => b.TherapyProgram)
                .Include(b => b.Parent);

            // Filter by selected month if provided
            if (selectedMonth.HasValue)
            {
                billingsQuery = billingsQuery.Where(b => b.Date.Month == selectedMonth.Value);
            }

            // Filter by payment status if provided
            if (paymentStatus.HasValue)
            {
                billingsQuery = billingsQuery.Where(b => b.PaymentStatus == paymentStatus.Value);
            }

            var billings = billingsQuery.ToList();

            return new ViewAsPdf("BillingPdf", billings)
            {
                FileName = "billing_report.pdf", // Set the file name for the PDF download
                PageSize = Rotativa.AspNetCore.Options.Size.A4
            };
        }

        // GET: Admin/Billings/Create
        public IActionResult Create()
        {
            ViewData["ParentId"] = new SelectList(_context.Parents, "ParentId", "Name");
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name");
            ViewData["TherapyProgramId"] = new SelectList(_context.TherapyPrograms, "Id", "Name");
            return View();
        }

        // POST: Admin/Billings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Amount,Date,PaymentReceipt,StudentId,PaymentStatus,TherapyProgramId,ParentId")] Billing billing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(billing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Parents, "ParentId", "Name", billing.ParentId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name", billing.StudentId);
            ViewData["TherapyProgramId"] = new SelectList(_context.TherapyPrograms, "Id", "Name", billing.TherapyProgramId);
            return View(billing);
        }

        // GET: Admin/Billings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billing = await _context.Billings.FindAsync(id);
            if (billing == null)
            {
                return NotFound();
            }
            ViewData["ParentId"] = new SelectList(_context.Parents, "ParentId", "Name", billing.ParentId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name", billing.StudentId);
            ViewData["TherapyProgramId"] = new SelectList(_context.TherapyPrograms, "Id", "Name", billing.TherapyProgramId);
            return View(billing);
        }

        // POST: Admin/Billings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PaymentStatus,Amount,Date,PaymentReceipt,StudentId,TherapyProgramId,ParentId")] Billing billing)
        {
            if (id != billing.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingBilling = await _context.Billings
                        .Include(b => b.Parent)
                        .Include(b => b.Student)
                        .Include(b => b.TherapyProgram)
                        .FirstOrDefaultAsync(b => b.Id == id);

                    if (existingBilling == null)
                    {
                        return NotFound();
                    }

                    // Only update the payment status
                    existingBilling.PaymentStatus = billing.PaymentStatus;

                    _context.Update(existingBilling);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillingExists(billing.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            // Re-populate the required fields before returning the view
            var billingToEdit = await _context.Billings
                .Include(b => b.Parent)
                .Include(b => b.Student)
                .Include(b => b.TherapyProgram)
                .FirstOrDefaultAsync(b => b.Id == id);

            if (billingToEdit == null)
            {
                return NotFound();
            }

            ViewBag.StudentId = new SelectList(_context.Students, "Id", "Name", billingToEdit.StudentId);
            ViewBag.TherapyProgramId = new SelectList(_context.TherapyPrograms, "Id", "Name", billingToEdit.TherapyProgramId);
            ViewBag.ParentId = new SelectList(_context.Parents, "ParentId", "Name", billingToEdit.ParentId);

            return View(billingToEdit);
        }





        // GET: Admin/Billings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billing = await _context.Billings
                .Include(b => b.Parent)
                .Include(b => b.Student)
                .Include(b => b.TherapyProgram)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (billing == null)
            {
                return NotFound();
            }

            return View(billing);
        }

        // POST: Admin/Billings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var billing = await _context.Billings.FindAsync(id);
            if (billing != null)
            {
                _context.Billings.Remove(billing);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GeneratePdfDetail(int id)
        {
            var billing = _context.Billings

Admin/Controllers/TherapyProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Therapi.Utility;
using TherapiCareTest.Data;
using TherapiCareTest.Models;
using TherapiCareTest.Repository.IRepository;

namespace TherapiCareTest.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class TherapyProgramController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public TherapyProgramController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<TherapyProgram> objTherapyProgramList = _unitOfWork.TherapyProgram.GetAll().ToList();
            return View(objTherapyProgramList);
        }
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            TherapyProgram? therapyProgramFromDb = _unitOfWork.TherapyProgram.Get(u => u.Id == id);

            if (therapyProgramFromDb == null)
            {
                return NotFound();
            }
            return View(therapyProgramFromDb);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TherapyProgram obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.TherapyProgram.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Program created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            TherapyProgram? therapyProgramFromDb = _unitOfWork.TherapyProgram.Get(u => u.Id == id);

            if (therapyProgramFromDb == null)
            {
                return NotFound();
            }
            return View(therapyProgramFromDb);
        }
        [HttpPost]
        public IActionResult Edit(TherapyProgram obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.TherapyProgram.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Program updated successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        #region API CALLS

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.TherapyProgram.Get(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.TherapyProgram.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Program deleted successfully" });
        }
        #endregion  
    }
}

Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Therapi.Utility;
using TherapiCareTest.Models;
using TherapiCareTest.Repository.IRepository;
using TherapiCareTest.ViewModels;

namespace TherapiCareTest.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RoleManagement(string userId)
        {
            var applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
            if (applicationUser == null)
            {
                return NotFound(); // Handle case where user is not found
            }

            var roles = _userManager.GetRolesAsync(applicationUser).Result;
            var roleList = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Name
            }).ToList();

            var roleManagementVM = new RoleManagementVM
            {
                ApplicationUser = applicationUser,
                RoleList = roleList,
                SelectedRole = roles.FirstOrDefault() // Optionally, set the selected role in case you want to preselect the current role
            };

            return View(roleManagementVM);
        }

        [HttpPost]
        public IActionResult RoleManagement(RoleManagementVM model)
        {
            var user = _unitOfWork.ApplicationUser.Get(u => u.Id == model.ApplicationUser.Id);
            if (user == null)
            {
                return NotFound(); 
            }

            var currentRoles = _userManager.GetRolesAsync(user).Result;
            var removeResult = _userManager.RemoveFromRolesAsync(user, currentRoles).Result;
            if (!removeResult.Succeeded)
            {
                ModelState.AddModelError("", "Failed to remove current roles.");
            }

            var addResult = _userManager.AddToRoleAsync(user, model.SelectedRole).Result;
            if (!addResult.Succeeded)
            {
                ModelState.AddModelError("", "Failed to add new role.");
            }

            model.RoleList = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Name
            });

            if (!ModelState.IsValid)
            {
                return View(model); 
            }

            _unitOfWork.Save();

            TempData["Success"] = "Role updated successfully.";
            return RedirectToAction("Index");
        }



        #region API

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> userList = _unitOfWork.ApplicationUser.GetAll().ToList();

            foreach (var user in userList)
            {
                var roles = _userManager.GetRolesAsync(user).Result;
                user.Role = roles.FirstOrDefault();
            }

            return Json(new { data = userList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var userObj = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
            if (userObj == null)
            {
                return Json(new { success = false, message = "Error while locking/unlocking" });
            }

            if (userObj.LockoutEnd > DateTime.Now)
            {
                userObj.LockoutEnd = DateTime.Now;
            }
            else
            {
                userObj.LockoutEnd = DateTime.Now.AddYears(1000);
            }

            _unitOfWork.ApplicationUser.Update(userObj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Operation successful" });
        }

        #endregion
    }
}

Admin/Views/Billings/Create.cshtml
@using TherapiCareTest.Data.Enum
@model TherapiCareTest.Models.Billing

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="Home" asp-action="Index" class="app-brand-link">
            <span class="app-brand-text demo menu-text fw-bolder ms-2">TherapiCare</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>
    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item ">
            <a class="menu-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" asp-area="Admin" asp-controller="TherapyProgram" asp-action="Index">
                <i class="menu-icon tf-icons bx bx-collection"></i>
                <div data-i18n="Analytics">Program</div>
            </a>
        </li>
        <li class="menu-item active">
            <a class="menu-link" asp-area="Admin" asp-controller="Billings" asp-action="Index">
                <i class="menu-icon tf-icons bi bi-cash"></i>
                <div data-i18n="Analytics">Billings</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Admin" asp-controller="AdminList" asp-action="ListOfStudent" class="menu-link">
                <i class="menu-icon tf-icons bi bi-people"></i>
                <div data-i18n="Basic">Student List</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Admin" asp-controller="AdminList" asp-action="ListOfParent" class="menu-link">
                <i class="menu-icon tf-icons bi bi-people"></i>
                <div data-i18n="Basic">Parent List</div>
            </a>
        </li>
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bi bi-person"></i>
                <div data-i18n="Account Settings">Manage User</div>
            </a>
            <ul class="menu-sub">
                <li class="menu-item">
                    <a class="menu-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                        <div data-i18n="Account">User List</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" asp-area="Identity" asp-page="/Account/Register">
                        <div data-i18n="Notifications">Register Staff</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item ">
            <a asp-area="Admin" asp-controller="Announcements" asp-action="Index" class="menu-link">

                <i class="flex-shrink-0 bx bi-megaphone me-2"></i>
                <div data-i18n="Basic"> Announcement</div>
            </a>
        </li>
    </ul>
</aside>

<div class="card-body p-4">
    <div class="row pb-3">
        <div class="col-6">
            <h3 class="fw-bold py-3 mb-2"><span class="text-muted fw-light">Billings /</span> Create Billing</h3>
        </div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentReceipt" class="control-label"></label>
                <input asp-for="PaymentReceipt" class="form-control" />
                <span asp-validation-for="PaymentReceipt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PaymentStatus" class="control-label"></label>
                <select asp-for="PaymentStatus" class="form-control" asp-items="@Html.GetEnumSelectList<PaymentStatus>()"></select>
                <span asp-validation-for="PaymentStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TherapyProgramId" class="control-label"></label>
                <select asp-for="TherapyProgramId" class ="form-control" asp-items="ViewBag.TherapyProgramId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class ="form-control" asp-items="ViewBag.ParentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Admin/Views/Billings/Delete.cshtml
@model TherapiCareTest.Models.Billing

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="Home" asp-action="Index" class="app-brand-link">
            <span class="app-brand-text demo menu-text fw-bolder ms-2">TherapiCare</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>
    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item ">
            <a class="menu-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link" asp-area="Admin" asp-controller="TherapyProgram" asp-action="Index">
                <i class="menu-icon tf-icons bx bx-collection"></i>
                <div data-i18n="Analytics">Program</div>
            </a>
        </li>
        <li class="menu-item active">
            <a class="menu-link" asp-area="Admin" asp-controller="Billings" asp-action="Index">
                <i class="menu-icon tf-icons bi bi-cash"></i>
                <div data-i18n="Analytics">Billings</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Admin" asp-controller="AdminList" asp-action="ListOfStudent" class="menu-link">
                <i class="menu-icon tf-icons bi bi-people"></i>
                <div data-i18n="Basic">Student List</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-area="Admin" asp-controller="AdminList" asp-action="ListOfParent" class="menu-link">
                <i class="menu-icon tf-icons bi bi-people"></i>
                <div data-i18n="Basic">Parent List</div>
            </a>
        </li>
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bi bi-person"></i>
                <div data-i18n="Account Settings">Manage User</div>
            </a>
            <ul class="menu-sub">
                <li class="menu-item">
                    <a class="menu-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                        <div data-i18n="Account">User List</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" asp-area="Identity" asp-page="/Account/Register">
                        <div data-i18n="Notifications">Register Staff</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item ">
            <a asp-area="Admin" asp-controller="Announcements" asp-action="Index" class="menu-link">

                <i class="flex-shrink-0 bx bi-megaphone me-2"></i>
                <div data-i18n="Basic"> Announcement</div>
            </a>
        </li>
    </ul>
</aside>
<h2 class="fw-bold py-3 mb-2">Delete Bill</h2>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentReceipt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentReceipt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TherapyProgram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TherapyProgram.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>